extends: eslint:recommended

# parser: babel-eslint
# parserOptions:
#   ecmaVersion: 2020
#   sourceType: module

env:
  commonjs: true
  node: true
  es2020: true

rules:
  no-console: error
  complexity:
    - error
    - max: 6
  max-depth:
    - error
    - max: 2
  max-nested-callbacks:
    - error
    - max: 2
  max-params:
    - error
    - max: 4
  max-statements:
    - error
    - max: 10
    - ignoreTopLevelFunctions: false
  max-len:
    - error
    - code: 120
      ignoreUrls: true
  max-lines:
    - error
    - max: 130
      skipComments: true
      skipBlankLines: true
  semi:
    - error
    - always
  no-multiple-empty-lines:
    - error
    - max: 1
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
